version: '3.8'

services:
  app:
    build: .
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - backend
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:

